image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
environment:
  matrix:
    # Python 3.8
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

max_jobs: 1

test_script:
  - "%PYTHON%\\python.exe setup.py install"
  - "%PYTHON%\\Scripts\\hdxpop -h"
