version: 1.0.{build}
image: 
  - Visual Studio 2019
  - Ubuntu
  - macOS

build: off

for:
  -
    matrix:
      only:
        - image: Ubuntu
    environment:
      stack: python 3.5
    test_script:
      - "source $HOME/venv3.8.2/bin/activate"
      - "python setup.py install"
      - "hdxpop -h"
  -
    matrix:
      only:
        - image: macOS
    environment:
      PYTHON: "python3"
    test_script:
      - "python3 setup.py install"
      - "hdxpop -h"
  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      PYTHON: "C:\\Python38-x64"
    test_script:
      - "%PYTHON%\\python setup.py install"
      - "hdxpop -h"
