version: 1.0.{build}
image: 
  - Visual Studio 2019
  - Ubuntu
# environment:
#   matrix:
#     - Windows: Visual Studio 2019
#     - Ubuntu: Ubuntu

build: off

for:
  -
    matrix:
      only:
        - image: Ubuntu
    environment:
      PYTHON: "python3"
    test_script:
      - "python3 --version"

  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      PYTHON: "C:\\Python38-x64"
    test_script:
      - "%PYTHON%\\python setup.py install"
